name: Container Demonstration

on: 
  push:
    branches:
      - main

jobs:
  node-docker:
    runs-on:  ubuntu-latest
    container:
      image:  docker.io/smartbear/ready-api-soapui-testrunner:latest
    steps:
      - name: ReadyAPI suite
        run:  |
          /usr/local/smartbear/readyapi/bin/testrunner.sh -f$(workspaces.output.path) -e $api_url "-s$api_url code coverage" -g "-RData Export" -FXML "-EDefault environment" -x=$password $(workspaces.output.path)/CODE_COVERAGE/$teamname/ReadyAPI_Test_Suite/HADRSUITE_45APIs.xml -accessKey $accessKey
